### ISSUE TITLE
Passing `self` unnecessarily

### ISSUE THREAD

**Issue by Enzime** [MatthewCroughan/nixcfg#2]
Hey,

I was taking a look at your dotfiles and I happened to notice you're passing `self` to `home.nix` to be able to reference files but Nix already supports it natively if I'm not mistaken:

```nix
home.file."scripts".source = "${self}/scripts";
```

is equivalent to

```nix
home.file."scripts".source = "${../../scripts}";
```

**Comment by MatthewCroughan** [comment]
If I use `${self}` it means I can move these files anywhere in the repo, and I no longer have to keep track of how many levels deep the Nix file is. `${self}` will always refer to the root of the flake, which is the root of the repo. This is preferential to `../../../../../../thing` for me.

**Comment by Enzime** [comment]
That makes sense 👍
