### ISSUE TITLE
What's the point of having private keys in the repository?

### ISSUE THREAD

**Issue by alurm** [MatthewCroughan/nixcfg#5]
https://github.com/MatthewCroughan/nixcfg/tree/master/users/matthew/modules/ssh has multiple private keys. Why?

Edit: I tried running `ssh-keygen -yf` over one of them. Seems not to be encrypted.

Edit: this is a FIDO backed key.

https://www.openssh.com/txt/release-8.2

>  The private key file should be useless to an attacker who does not have access to the physical token.

Thanks for sharing the configuration.

Edit: to be clear, not understanding if there's an advantage to this approach over storing the key on the second factor.

https://security.stackexchange.com/questions/270137/can-someone-with-access-to-only-my-yubikey-gain-access-to-my-server-that-has-ssh

> an attacker who steals your YubiKey but has no access to the SSH “private key” file cannot authenticate at your server, because the YubiKey itself doesn't contain any data whatsoever about the private key.

**Comment by MatthewCroughan** [comment]
@alurm

> storing the key on the second factor.

What does this mean?

**Comment by alurm** [comment]
> What does this mean?

https://security.stackexchange.com/questions/270137/can-someone-with-access-to-only-my-yubikey-gain-access-to-my-server-that-has-ssh

> The second option (using -O resident) is to actually store the private key on the YubiKey. Then you don't need any SSH “private key” file at all for SSH authentication. Of course that means an attacker who has full access to the YubiKey can use it to authenticate at your server.

This is what I meant. I haven't used such devices myself, so I may be missing something.

**Comment by MatthewCroughan** [comment]
You still only have an 8 in 36⁶³ chance of correctly guessing my FIDO2 pin. So you will have to beat me with a wrench first.
